# Generated by Django 5.2.3 on 2025-08-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='requirements',
            field=models.TextField(blank=True, help_text='One requirement per line.', null=True),
        ),
    ]
