# Generated by Django 5.2.3 on 2025-08-06 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikipage',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
