# Generated by Django 5.2.3 on 2025-08-06 22:24

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_wikipage_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikipage',
            name='content',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
