# Generated by Django 5.2.3 on 2025-08-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_alter_wikipage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikipage',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
