# Generated by Django 5.2.3 on 2025-09-06 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('url', models.URLField()),
                ('active', models.BooleanField(default=True)),
                ('clicks', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
