# Generated by Django 5.2.3 on 2025-09-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0002_affiliatelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliatelink',
            name='signups_from_clicks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
