# Generated by Django 5.2.3 on 2025-07-06 23:43

import django.db.models.deletion
import gameData.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=100)),
                ('routes_json_file', models.FileField(blank=True, null=True, upload_to='JSON/gameRoutes/')),
                ('dests_json_file', models.FileField(blank=True, null=True, upload_to='JSON/gameRoutes/Dests')),
                ('details', models.JSONField(default=gameData.models.game_details)),
            ],
        ),
        migrations.CreateModel(
            name='game_tiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiles_json_file', models.FileField(blank=True, null=True, upload_to='JSON/gameTiles/')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameData.game')),
            ],
        ),
    ]
