# Generated by Django 5.2.3 on 2025-09-05 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameData', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
