# Generated by Django 5.2 on 2025-04-14 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybustimes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleetchange',
            name='operator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='history_operator_id', to='mybustimes.mbtoperator'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fleetchange',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_vehicle_id', to='mybustimes.fleet'),
        ),
    ]
