# Generated by Django 5.1.7 on 2025-04-01 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybustimes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='badges',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
