# Generated by Django 5.2 on 2025-04-15 00:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybustimes', '0002_fleetchange_operator_alter_fleetchange_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleetchange',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
