# Generated by Django 5.2 on 2025-04-15 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybustimes', '0003_alter_fleetchange_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleet',
            name='last_modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fleet_modified_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
