# Generated by Django 5.1.7 on 2025-04-01 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybustimes', '0003_alter_customuser_badges'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='static_ticketer_code',
            field=models.BooleanField(default=True),
        ),
    ]
