# Generated by Django 5.1.7 on 2025-04-01 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybustimes', '0004_customuser_static_ticketer_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('css', models.TextField()),
                ('header_css', models.TextField()),
                ('dark_theme', models.BooleanField(default=False)),
            ],
        ),
    ]
