# Generated by Django 5.2 on 2025-04-15 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybustimes', '0004_alter_fleet_last_modified_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleet',
            name='livery',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mybustimes.liverie'),
        ),
    ]
