# Generated by Django 5.1.7 on 2025-04-01 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybustimes', '0005_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='theme_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
