# Generated by Django 5.2 on 2025-04-15 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybustimes', '0006_alter_fleet_livery'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='type',
            new_name='vehicleType',
        ),
        migrations.RenameField(
            model_name='fleet',
            old_name='type',
            new_name='vehicleType',
        ),
    ]
