# Generated by Django 5.1.7 on 2025-04-01 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybustimes', '0006_theme_theme_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='header_css',
        ),
    ]
