# Generated by Django 5.2 on 2025-04-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybustimes', '0007_rename_type_vehicletype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='route_num',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
