# Generated by Django 5.2 on 2025-04-03 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybustimes', '0007_remove_theme_header_css'),
    ]

    operations = [
        migrations.CreateModel(
            name='liveries',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('livery_name', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=False)),
                ('css', models.TextField()),
                ('added_by', models.CharField(max_length=50)),
                ('aproved_by', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='types',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=False)),
                ('double_decker', models.BooleanField(default=False)),
                ('lengths', models.TextField()),
                ('type', models.CharField(default='Bus', max_length=50)),
                ('added_by', models.CharField(max_length=50)),
                ('aproved_by', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='fleet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fleet_number', models.CharField(max_length=50)),
                ('operator_code', models.CharField(max_length=4)),
                ('load_operator_code', models.CharField(max_length=4)),
                ('reg', models.CharField(max_length=50)),
                ('prev_reg', models.TextField()),
                ('colour', models.CharField(max_length=50)),
                ('type_details', models.CharField(max_length=50)),
                ('in_service', models.BooleanField(default=True)),
                ('for_sale', models.BooleanField(default=False)),
                ('preserved', models.BooleanField(default=False)),
                ('on_load', models.BooleanField(default=False)),
                ('open_top', models.BooleanField(default=False)),
                ('branding', models.CharField(max_length=50)),
                ('depot', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('length', models.CharField(max_length=50)),
                ('features', models.TextField()),
                ('notes', models.TextField()),
                ('livery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybustimes.liveries')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybustimes.types')),
            ],
        ),
    ]
