# Generated by Django 5.2 on 2025-04-17 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybustimes', '0008_alter_route_route_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='route_operator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mybustimes.mbtoperator'),
            preserve_default=False,
        ),
    ]
