# Generated by Django 5.2 on 2025-04-03 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybustimes', '0008_liveries_types_fleet'),
    ]

    operations = [
        migrations.CreateModel(
            name='FleetChangeLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('changed_fields', models.TextField()),
                ('old_values', models.JSONField()),
                ('new_values', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('fleet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='mybustimes.fleet')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
