# Generated by Django 5.2 on 2025-04-03 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybustimes', '0009_fleetchangelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='types',
            name='fuel',
            field=models.CharField(default='Diesel', max_length=50),
        ),
    ]
