# Generated by Django 5.2 on 2025-04-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybustimes', '0009_alter_route_route_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='linked_route',
            field=models.ManyToManyField(blank=True, related_name='linked_routes', to='mybustimes.route'),
        ),
    ]
