# Generated by Django 5.2 on 2025-04-03 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybustimes', '0010_types_fuel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleet',
            name='branding',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='colour',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='depot',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='features',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='length',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='load_operator_code',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='prev_reg',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='reg',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='type_details',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='types',
            name='lengths',
            field=models.TextField(blank=True),
        ),
    ]
