# Generated by Django 5.2 on 2025-04-17 19:47

import mybustimes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybustimes', '0010_route_linked_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='other_destination',
            field=models.JSONField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='route',
            name='route_details',
            field=models.JSONField(blank=True, default=mybustimes.models.default_route_details),
        ),
    ]
