# Generated by Django 5.2 on 2025-04-04 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybustimes', '0011_alter_fleet_branding_alter_fleet_colour_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='groups',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=50)),
                ('group_owner', models.CharField()),
                ('private', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='organisations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('organisation_name', models.CharField(max_length=50)),
                ('organisation_owner', models.CharField()),
                ('private', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='operators',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('operator_name', models.CharField(max_length=50)),
                ('operator_code', models.CharField(max_length=4)),
                ('operator_details', models.JSONField(blank=True, null=True)),
                ('private', models.BooleanField(default=False)),
                ('public', models.BooleanField(default=False)),
                ('show_trip_id', models.BooleanField(default=True)),
                ('region', models.TextField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybustimes.groups')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybustimes.organisations')),
            ],
        ),
    ]
