# Generated by Django 5.2 on 2025-04-17 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybustimes', '0011_route_other_destination_alter_route_route_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='other_destination',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
