# Generated by Django 5.2 on 2025-04-04 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybustimes', '0012_groups_organisations_operators'),
    ]

    operations = [
        migrations.AddField(
            model_name='operators',
            name='owner',
            field=models.CharField(default='admin', max_length=50),
        ),
        migrations.AlterField(
            model_name='groups',
            name='group_owner',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='organisations',
            name='organisation_owner',
            field=models.CharField(max_length=50),
        ),
    ]
