# Generated by Django 5.2 on 2025-04-17 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybustimes', '0012_alter_route_other_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='other_route_operator',
            field=models.ManyToManyField(blank=True, related_name='route_other_operators', to='mybustimes.mbtoperator'),
        ),
    ]
