# Generated by Django 5.2 on 2025-04-04 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybustimes', '0013_operators_owner_alter_groups_group_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operators',
            name='region',
            field=models.JSONField(default=['United Kingdom']),
        ),
    ]
