# Generated by Django 5.2 on 2025-04-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybustimes', '0013_route_other_route_operator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='other_route_operator',
        ),
        migrations.RemoveField(
            model_name='route',
            name='route_operator',
        ),
        migrations.AddField(
            model_name='route',
            name='route_operators',
            field=models.ManyToManyField(related_name='route_other_operators', to='mybustimes.mbtoperator'),
        ),
    ]
