# Generated by Django 5.2 on 2025-04-17 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybustimes', '0014_remove_route_other_route_operator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='related_route',
            field=models.ManyToManyField(blank=True, related_name='related_routes', to='mybustimes.route'),
        ),
    ]
