# Generated by Django 5.2 on 2025-04-04 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybustimes', '0014_alter_operators_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operators',
            name='region',
            field=models.JSONField(default=['region']),
        ),
    ]
