# Generated by Django 5.2 on 2025-04-18 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybustimes', '0015_route_related_route'),
    ]

    operations = [
        migrations.DeleteModel(
            name='route',
        ),
    ]
