# Generated by Django 5.2 on 2025-04-04 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybustimes', '0016_alter_operators_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operators',
            name='region',
            field=models.JSONField(default={'region': ['United Kingdom']}),
        ),
    ]
