# Generated by Django 5.2 on 2025-04-04 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybustimes', '0017_alter_operators_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operators',
            name='operator_details',
            field=models.JSONField(blank=True, default={'twitter': '@example', 'website': 'https://example.com'}, null=True),
        ),
    ]
