# Generated by Django 5.2 on 2025-04-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybustimes', '0018_alter_operators_operator_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='regions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=100, unique=True)),
                ('region_code', models.CharField(max_length=2, unique=True)),
                ('in_the', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='operators',
            name='region',
        ),
        migrations.AddField(
            model_name='operators',
            name='region',
            field=models.ManyToManyField(related_name='operators', to='mybustimes.regions'),
        ),
    ]
