# Generated by Django 5.2 on 2025-04-21 00:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybustimes', '0018_loginiphashlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuretoggle',
            name='coming_soon_percent',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
