# Generated by Django 5.2 on 2025-04-21 00:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybustimes', '0019_featuretoggle_coming_soon_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuretoggle',
            name='coming_soon_percent',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
