# Generated by Django 5.2 on 2025-04-04 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybustimes', '0019_regions_remove_operators_region_operators_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='regions',
            name='region_country',
            field=models.CharField(default='England', max_length=100),
        ),
    ]
