# Generated by Django 5.2 on 2025-04-04 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybustimes', '0020_regions_region_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regions',
            name='region_code',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
