# Generated by Django 5.2 on 2025-04-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybustimes', '0020_alter_featuretoggle_coming_soon_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='MBTAdminPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'MBT Admin Permission',
                'verbose_name_plural': 'MBT Admin Permissions',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='mbt_admin_perms',
            field=models.ManyToManyField(blank=True, help_text='Administrative permissions for MyBusTimes', related_name='users_with_perm', to='mybustimes.mbtadminpermission'),
        ),
    ]
