# Generated by Django 5.2 on 2025-04-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybustimes', '0021_mbtadminpermission_customuser_mbt_admin_perms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='css',
            field=models.ImageField(upload_to='themes/'),
        ),
    ]
