# Generated by Django 5.2 on 2025-04-04 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybustimes', '0021_alter_regions_region_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operators',
            name='group',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mybustimes.groups'),
        ),
    ]
