# Generated by Django 5.2 on 2025-04-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybustimes', '0022_alter_theme_css'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='css',
            field=models.FileField(help_text='Upload a CSS file', upload_to='themes/'),
        ),
    ]
