# Generated by Django 5.2 on 2025-04-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybustimes', '0023_alter_theme_css'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
