# Generated by Django 5.2 on 2025-04-04 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybustimes', '0023_alter_operators_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operators',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mybustimes.groups'),
        ),
    ]
