# Generated by Django 5.2 on 2025-04-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybustimes', '0024_theme_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='serviceUpdate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('live', models.BooleanField(default=False)),
            ],
        ),
    ]
