# Generated by Django 5.2 on 2025-04-05 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybustimes', '0024_alter_operators_group'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='liveries',
            new_name='liverie',
        ),
        migrations.RenameModel(
            old_name='types',
            new_name='type',
        ),
        migrations.RenameModel(
            old_name='groups',
            new_name='group',
        ),
        migrations.RenameModel(
            old_name='organisations',
            new_name='organisation',
        ),
        migrations.RenameModel(
            old_name='regions',
            new_name='region',
        ),
        migrations.CreateModel(
            name='operator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('operator_name', models.CharField(max_length=50)),
                ('operator_code', models.CharField(max_length=4)),
                ('operator_details', models.JSONField(blank=True, default={'game': 'OMSI2', 'twitter': '@example', 'type': 'real-company', 'website': 'https://example.com'}, null=True)),
                ('private', models.BooleanField(default=False)),
                ('public', models.BooleanField(default=False)),
                ('show_trip_id', models.BooleanField(default=True)),
                ('owner', models.CharField(default='admin', max_length=50)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mybustimes.group')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybustimes.organisation')),
                ('region', models.ManyToManyField(related_name='operators', to='mybustimes.region')),
            ],
        ),
        migrations.CreateModel(
            name='route',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('route_num', models.CharField(max_length=50)),
                ('route_name', models.CharField(max_length=4)),
                ('route_details', models.JSONField(blank=True, default={'details': {'cash': 'true', 'contactless': 'true', 'school_service': 'false'}, 'route_colour': 'var(--background-color)', 'route_text_colour': 'var(--text-color)'}, null=True)),
                ('route_operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mybustimes.operator')),
            ],
        ),
        migrations.DeleteModel(
            name='operators',
        ),
    ]
