# Generated by Django 5.2 on 2025-04-05 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybustimes', '0025_rename_liveries_liverie_rename_types_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='inboud_destination',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='outboud_destination',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='operator',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mybustimes.organisation'),
        ),
    ]
