# Generated by Django 5.2 on 2025-04-27 17:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybustimes', '0025_serviceupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceupdate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceupdate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
