# Generated by Django 5.2 on 2025-04-05 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybustimes', '0026_route_inboud_destination_route_outboud_destination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='route_name',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
