# Generated by Django 5.2 on 2025-04-28 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybustimes', '0026_serviceupdate_created_at_serviceupdate_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='organisation_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisation_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
