# Generated by Django 5.2 on 2025-04-28 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybustimes', '0027_alter_group_group_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='private',
        ),
    ]
