# Generated by Django 5.2 on 2025-04-05 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybustimes', '0027_alter_route_route_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_name', models.CharField(max_length=100)),
                ('ad_img', models.ImageField(upload_to='images/')),
                ('ad_link', models.TextField()),
            ],
        ),
    ]
