# Generated by Django 5.2 on 2025-04-06 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybustimes', '0028_ad'),
    ]

    operations = [
        migrations.CreateModel(
            name='badge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('badge_name', models.CharField(max_length=50)),
                ('badge_backgroud', models.TextField()),
                ('badge_text_color', models.CharField(max_length=7)),
                ('additional_css', models.TextField(blank=True, null=True)),
                ('self_asign', models.BooleanField(default=True)),
            ],
        ),
    ]
