# Generated by Django 5.2 on 2025-04-29 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybustimes', '0028_remove_organisation_private'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('admin_dash', 'Can access the admin dashboard')]},
        ),
    ]
