# Generated by Django 5.2 on 2025-04-06 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybustimes', '0029_badge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='self_asign',
            field=models.BooleanField(default=False),
        ),
    ]
