# Generated by Django 5.2 on 2025-04-29 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybustimes', '0029_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
