# Generated by Django 5.2 on 2025-04-06 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybustimes', '0030_alter_badge_self_asign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='badges',
        ),
        migrations.AddField(
            model_name='customuser',
            name='badges',
            field=models.ManyToManyField(related_name='badges', to='mybustimes.badge'),
        ),
    ]
