# Generated by Django 5.2 on 2025-04-06 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybustimes', '0031_remove_customuser_badges_customuser_badges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleet',
            name='operator_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mybustimes.operator'),
        ),
    ]
