# Generated by Django 5.2 on 2025-04-06 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybustimes', '0032_alter_fleet_operator_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fleet',
            name='load_operator_code',
        ),
        migrations.RemoveField(
            model_name='fleet',
            name='operator_code',
        ),
        migrations.AddField(
            model_name='fleet',
            name='load_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fleet_load_operator', to='mybustimes.operator'),
        ),
        migrations.AddField(
            model_name='fleet',
            name='operator',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fleet_operator', to='mybustimes.operator'),
            preserve_default=False,
        ),
    ]
