# Generated by Django 5.2 on 2025-04-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybustimes', '0033_remove_fleet_load_operator_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='main_colour',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
