# Generated by Django 5.2 on 2025-04-08 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybustimes', '0034_theme_main_colour'),
    ]

    operations = [
        migrations.CreateModel(
            name='featureToggle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('enabled', models.BooleanField(default=False)),
            ],
        ),
    ]
