# Generated by Django 5.2 on 2025-04-08 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybustimes', '0035_featuretoggle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuretoggle',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
