# Generated by Django 5.2 on 2025-04-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybustimes', '0036_alter_featuretoggle_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuretoggle',
            name='maintenance',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='badges',
            field=models.ManyToManyField(blank=True, null=True, related_name='badges', to='mybustimes.badge'),
        ),
    ]
