# Generated by Django 5.2 on 2025-04-09 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybustimes', '0037_featuretoggle_maintenance_alter_customuser_badges'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuretoggle',
            name='coming_soon',
            field=models.BooleanField(default=False),
        ),
    ]
