# Generated by Django 5.2 on 2025-04-09 20:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybustimes', '0038_featuretoggle_coming_soon'),
    ]

    operations = [
        migrations.CreateModel(
            name='update',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('tages', models.TextField()),
                ('link', models.TextField(blank=True, null=True)),
                ('readBy', models.ManyToManyField(blank=True, related_name='read_updates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
