# Generated by Django 5.2 on 2025-04-09 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybustimes', '0039_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fleet',
            name='load_operator',
        ),
        migrations.AddField(
            model_name='fleet',
            name='loan_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fleet_loan_operator', to='mybustimes.operator'),
        ),
    ]
