# Generated by Django 5.2 on 2025-04-10 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybustimes', '0040_remove_fleet_load_operator_fleet_loan_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleet',
            name='last_tracked_date',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='fleet',
            name='last_tracked_time',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
