# Generated by Django 5.2 on 2025-04-10 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybustimes', '0041_fleet_last_tracked_date_fleet_last_tracked_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fleet',
            old_name='last_tracked_time',
            new_name='last_tracked_route',
        ),
        migrations.AlterField(
            model_name='fleet',
            name='last_tracked_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
