# Generated by Django 5.2 on 2025-04-10 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybustimes', '0042_rename_last_tracked_time_fleet_last_tracked_route_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleet',
            name='last_tracked_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
