# Generated by Django 5.2 on 2025-04-10 21:35

import mybustimes.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybustimes', '0043_alter_fleet_last_tracked_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('show_name', models.BooleanField(default=True)),
                ('colour', mybustimes.fields.ColourField(help_text='For the most simplified version of the livery', max_length=7)),
                ('colours', mybustimes.fields.ColoursField(blank=True, help_text='Left and right CSS will be generated from this', max_length=512)),
                ('angle', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('left_css', mybustimes.fields.CSSField(blank=True, help_text='Automatically generated from colours and angle', max_length=1024, verbose_name='Left CSS')),
                ('right_css', mybustimes.fields.CSSField(blank=True, help_text='Should be a mirror image of the left CSS', max_length=1024, verbose_name='Right CSS')),
                ('white_text', models.BooleanField(default=False)),
                ('text_colour', mybustimes.fields.ColourField(blank=True, max_length=7)),
                ('stroke_colour', mybustimes.fields.ColourField(blank=True, help_text='Use sparingly, often looks shit', max_length=7)),
                ('horizontal', models.BooleanField(default=False, help_text='Equivalent to setting the angle to 90')),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('published', models.BooleanField(default=False, help_text='Tick to include in the CSS and be able to apply this livery to vehicles')),
            ],
            options={
                'verbose_name_plural': 'liveries',
                'ordering': ('name',),
            },
        ),
    ]
