# Generated by Django 5.2 on 2025-04-10 21:43

import django.db.models.deletion
import mybustimes.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybustimes', '0044_livery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Livery',
        ),
        migrations.AlterModelOptions(
            name='liverie',
            options={'ordering': ('name',), 'verbose_name_plural': 'liveries'},
        ),
        migrations.RemoveField(
            model_name='liverie',
            name='active',
        ),
        migrations.RemoveField(
            model_name='liverie',
            name='css',
        ),
        migrations.RemoveField(
            model_name='liverie',
            name='livery_name',
        ),
        migrations.AddField(
            model_name='liverie',
            name='angle',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='liverie',
            name='colour',
            field=mybustimes.fields.ColourField(default='#ffffff', help_text='For the most simplified version of the livery', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='liverie',
            name='colours',
            field=mybustimes.fields.ColoursField(blank=True, help_text='Left and right CSS will be generated from this', max_length=512),
        ),
        migrations.AddField(
            model_name='liverie',
            name='horizontal',
            field=models.BooleanField(default=False, help_text='Equivalent to setting the angle to 90'),
        ),
        migrations.AddField(
            model_name='liverie',
            name='left_css',
            field=mybustimes.fields.CSSField(blank=True, help_text='Automatically generated from colours and angle', max_length=1024, verbose_name='Left CSS'),
        ),
        migrations.AddField(
            model_name='liverie',
            name='name',
            field=models.CharField(db_index=True, default='rename', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='liverie',
            name='published',
            field=models.BooleanField(default=False, help_text='Tick to include in the CSS and be able to apply this livery to vehicles'),
        ),
        migrations.AddField(
            model_name='liverie',
            name='right_css',
            field=mybustimes.fields.CSSField(blank=True, help_text='Should be a mirror image of the left CSS', max_length=1024, verbose_name='Right CSS'),
        ),
        migrations.AddField(
            model_name='liverie',
            name='show_name',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='liverie',
            name='stroke_colour',
            field=mybustimes.fields.ColourField(blank=True, help_text='Use sparingly, often looks shit', max_length=7),
        ),
        migrations.AddField(
            model_name='liverie',
            name='text_colour',
            field=mybustimes.fields.ColourField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='liverie',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='liverie',
            name='white_text',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='liverie',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='liverie',
            name='aproved_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aproved_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
