# Generated by Django 5.2 on 2025-04-10 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybustimes', '0045_delete_livery_alter_liverie_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liverie',
            name='angle',
        ),
        migrations.RemoveField(
            model_name='liverie',
            name='colours',
        ),
        migrations.RemoveField(
            model_name='liverie',
            name='horizontal',
        ),
    ]
