# Generated by Django 5.2 on 2025-04-11 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybustimes', '0046_remove_liverie_angle_remove_liverie_colours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
