# Generated by Django 5.2 on 2025-04-11 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybustimes', '0047_alter_operator_owner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='operator',
            new_name='MBTOperator',
        ),
    ]
