# Generated by Django 5.2 on 2025-04-11 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybustimes', '0048_rename_operator_mbtoperator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liverie',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livery_added_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='liverie',
            name='aproved_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livery_aproved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='type',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types_added_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='type',
            name='aproved_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types_aproved_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
