# Generated by Django 5.2 on 2025-04-12 01:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybustimes', '0049_alter_liverie_added_by_alter_liverie_aproved_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='helper_perm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('perm_name', models.CharField(max_length=50)),
                ('perms_level', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, help_text='Permission level from 1 (lowest) to 5 (highest)')),
            ],
        ),
        migrations.CreateModel(
            name='helper',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('helper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helper_users', to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='helper_operator', to='mybustimes.mbtoperator')),
                ('perms', models.ManyToManyField(related_name='helper_perms', to='mybustimes.helper_perm')),
            ],
        ),
    ]
