# Generated by Django 5.2 on 2025-04-12 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybustimes', '0050_helper_perm_helper'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='helper_perm',
            new_name='helperPerm',
        ),
    ]
