# Generated by Django 5.2 on 2025-04-12 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybustimes', '0051_rename_helper_perm_helperperm'),
    ]

    operations = [
        migrations.CreateModel(
            name='fleetChange',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('operator_new', models.CharField(max_length=50)),
                ('operator_old', models.CharField(max_length=50)),
                ('loan_operator_new', models.CharField(max_length=50)),
                ('loan_operator_old', models.CharField(max_length=50)),
                ('in_service_new', models.BooleanField()),
                ('in_service_old', models.BooleanField()),
                ('for_sale_new', models.BooleanField()),
                ('for_sale_old', models.BooleanField()),
                ('preserved_new', models.BooleanField()),
                ('preserved_old', models.BooleanField()),
                ('on_load_new', models.BooleanField()),
                ('on_load_old', models.BooleanField()),
                ('open_top_new', models.BooleanField()),
                ('open_top_old', models.BooleanField()),
                ('fleet_number_new', models.CharField(blank=True, max_length=50)),
                ('fleet_number_old', models.CharField(blank=True, max_length=50)),
                ('reg_new', models.CharField(blank=True, max_length=50)),
                ('reg_old', models.CharField(blank=True, max_length=50)),
                ('prev_reg_new', models.TextField(blank=True)),
                ('prev_reg_old', models.TextField(blank=True)),
                ('livery_name_new', models.CharField(blank=True, max_length=50)),
                ('livery_name_old', models.CharField(blank=True, max_length=50)),
                ('livery_css_new', models.TextField(blank=True)),
                ('livery_css_old', models.TextField(blank=True)),
                ('colour_new', models.CharField(blank=True, max_length=50)),
                ('colour_old', models.CharField(blank=True, max_length=50)),
                ('type_name_new', models.CharField(blank=True, max_length=50)),
                ('type_name_old', models.CharField(blank=True, max_length=50)),
                ('type_details_new', models.CharField(blank=True, max_length=50)),
                ('type_details_old', models.CharField(blank=True, max_length=50)),
                ('branding_new', models.CharField(blank=True, max_length=50)),
                ('branding_old', models.CharField(blank=True, max_length=50)),
                ('depot_new', models.CharField(blank=True, max_length=50)),
                ('depot_old', models.CharField(blank=True, max_length=50)),
                ('name_new', models.CharField(blank=True, max_length=50)),
                ('name_old', models.CharField(blank=True, max_length=50)),
                ('length_new', models.CharField(blank=True, max_length=50)),
                ('length_old', models.CharField(blank=True, max_length=50)),
                ('features_new', models.TextField(blank=True)),
                ('features_old', models.TextField(blank=True)),
                ('notes_new', models.TextField(blank=True)),
                ('notes_old', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybustimes.fleet')),
            ],
        ),
        migrations.DeleteModel(
            name='FleetChangeLog',
        ),
    ]
