# Generated by Django 5.2 on 2025-04-13 12:23

import mybustimes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybustimes', '0052_fleetchange_delete_fleetchangelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='badges',
            field=models.ManyToManyField(blank=True, related_name='badges', to='mybustimes.badge'),
        ),
        migrations.AlterField(
            model_name='route',
            name='route_details',
            field=models.JSONField(blank=True, default=mybustimes.models.default_route_details, null=True),
        ),
    ]
