# Generated by Django 5.2.3 on 2025-06-18 01:06

import django.db.models.deletion
import routes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gameData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dayType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='transitAuthoritiesColour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authority_code', models.CharField(max_length=100, unique=True)),
                ('primary_colour', models.CharField(default='#000000', max_length=7)),
                ('secondary_colour', models.CharField(default='#FFFFFF', max_length=7)),
            ],
            options={
                'verbose_name_plural': 'Transit Authorities Colours',
            },
        ),
        migrations.CreateModel(
            name='duty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty_name', models.CharField(max_length=100)),
                ('duty_details', models.JSONField(blank=True, null=True)),
                ('duty_day', models.ManyToManyField(related_name='duty_types', to='routes.daytype')),
            ],
        ),
        migrations.CreateModel(
            name='route',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('route_num', models.CharField(blank=True, max_length=50, null=True)),
                ('route_name', models.CharField(blank=True, max_length=255, null=True)),
                ('route_details', models.JSONField(blank=True, default=routes.models.default_route_details)),
                ('inboud_destination', models.CharField(blank=True, max_length=100, null=True)),
                ('outboud_destination', models.CharField(blank=True, max_length=100, null=True)),
                ('other_destination', models.JSONField(blank=True, null=True)),
                ('linked_route', models.ManyToManyField(blank=True, to='routes.route')),
                ('related_route', models.ManyToManyField(blank=True, to='routes.route')),
            ],
        ),
        migrations.CreateModel(
            name='dutyTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('start_at', models.CharField(blank=True, max_length=100, null=True)),
                ('end_at', models.CharField(blank=True, max_length=100, null=True)),
                ('duty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_trips', to='routes.duty')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_trips', to='routes.route')),
            ],
        ),
        migrations.CreateModel(
            name='serviceUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('update_details', models.JSONField()),
                ('effected_route', models.ManyToManyField(related_name='service_updates', to='routes.route')),
            ],
        ),
        migrations.CreateModel(
            name='stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('source', models.CharField(default='custom', max_length=20)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameData.game')),
            ],
        ),
        migrations.CreateModel(
            name='timetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inbound', models.BooleanField(default=True)),
                ('circular', models.BooleanField(default=False)),
                ('operator_schedule', models.JSONField()),
                ('stop_times', models.JSONField()),
                ('day_type', models.ManyToManyField(related_name='timetable_entries', to='routes.daytype')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.route')),
            ],
        ),
    ]
