# Generated by Django 5.2.3 on 2025-06-18 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_companyupdate_routes'),
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='duty',
            name='duty_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duties', to='fleet.mbtoperator'),
        ),
        migrations.AddField(
            model_name='route',
            name='route_operators',
            field=models.ManyToManyField(related_name='route_other_operators', to='fleet.mbtoperator'),
        ),
    ]
