# Generated by Django 5.2.3 on 2025-07-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_duty_duty_operator_route_route_operators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetableentry',
            name='stop_times',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
    ]
