# Generated by Django 5.2.3 on 2025-06-23 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_duty_duty_operator_route_route_operators'),
    ]

    operations = [
        migrations.CreateModel(
            name='routeStops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inbound', models.BooleanField(default=True)),
                ('circular', models.BooleanField(default=False)),
                ('stops', models.JSONField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.route')),
            ],
        ),
    ]
