# Generated by Django 5.2.3 on 2025-06-23 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_routestops'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='routeStops',
            new_name='routeStop',
        ),
    ]
