# Generated by Django 5.2.3 on 2025-07-12 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_alter_timetableentry_stop_times'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='start_date',
        ),
    ]
