# Generated by Django 5.2.3 on 2025-06-23 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_rename_routestops_routestop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='inboud_destination',
            new_name='inbound_destination',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='outboud_destination',
            new_name='outbound_destination',
        ),
    ]
