# Generated by Django 5.2.3 on 2025-07-12 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_remove_route_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
