# Generated by Django 5.2.3 on 2025-07-12 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0005_route_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceupdate',
            name='update_description',
        ),
        migrations.RemoveField(
            model_name='serviceupdate',
            name='update_title',
        ),
    ]
