# Generated by Django 5.2.3 on 2025-06-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0005_rename_inboud_destination_route_inbound_destination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dutytrip',
            name='route',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
