# Generated by Django 5.2.3 on 2025-06-29 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0006_alter_dutytrip_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dutytrip',
            name='route',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='duty_trips', to='routes.route'),
            preserve_default=False,
        ),
    ]
