# Generated by Django 5.2.3 on 2025-07-12 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0006_remove_serviceupdate_update_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceupdate',
            name='update_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceupdate',
            name='update_title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
