# Generated by Django 5.2.3 on 2025-07-24 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0007_serviceupdate_update_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetableentry',
            name='stop_times',
            field=models.TextField(blank=True, null=True),
        ),
    ]
