# Generated by Django 5.2.3 on 2025-06-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0007_alter_dutytrip_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dutytrip',
            name='route',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
