# Generated by Django 5.2.3 on 2025-08-06 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0008_alter_timetableentry_stop_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='dutytrip',
            name='route_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duty_trip_route', to='routes.route'),
        ),
    ]
