# Generated by Django 5.2.3 on 2025-06-30 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_alter_fleet_length'),
        ('routes', '0008_alter_dutytrip_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='runningBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('running_board_name', models.CharField(max_length=100)),
                ('running_board_details', models.JSONField(blank=True, null=True)),
                ('running_board_day', models.ManyToManyField(related_name='running_board_types', to='routes.daytype')),
                ('running_board_operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='running_boards', to='fleet.mbtoperator')),
            ],
        ),
        migrations.CreateModel(
            name='runningBoardTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(blank=True, max_length=100, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('start_at', models.CharField(blank=True, max_length=100, null=True)),
                ('end_at', models.CharField(blank=True, max_length=100, null=True)),
                ('running_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='running_board_trips', to='routes.runningboard')),
            ],
        ),
    ]
