# Generated by Django 5.2.3 on 2025-08-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0009_dutytrip_route_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='route_depot',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
