# Generated by Django 5.2.3 on 2025-06-30 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0009_runningboard_runningboardtrip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runningboardtrip',
            name='running_board',
        ),
        migrations.AddField(
            model_name='duty',
            name='type',
            field=models.CharField(choices=[('duty', 'Duty'), ('running_board', 'Running Board')], default='duty', max_length=20),
        ),
        migrations.DeleteModel(
            name='runningBoard',
        ),
        migrations.DeleteModel(
            name='runningBoardTrip',
        ),
    ]
