# Generated by Django 5.2.3 on 2025-06-30 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0010_remove_runningboardtrip_running_board_duty_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='duty',
            old_name='type',
            new_name='board_type',
        ),
    ]
