# Generated by Django 5.2.3 on 2025-07-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0011_rename_type_duty_board_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duty',
            name='board_type',
            field=models.CharField(choices=[('duty', 'Duty'), ('running_boards', 'Running Board')], default='duty', max_length=20),
        ),
    ]
