# Generated by Django 5.2.12 on 2026-05-30 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0018_add_category_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltimetableentry',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
