# Generated by Django 5.2.14 on 2026-07-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0052_alter_fleet_fleet_number_and_more'),
        ('routes', '0019_historicaltimetableentry_active_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['route_num'], name='routes_route_route_num_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['hidden', 'route_num'], name='route_hidden_rnum_idx'),
        ),
    ]
