# Generated by Django 5.2.14 on 2026-07-29 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0021_cleanup_duplicate_routestops'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='routestop',
            unique_together={('route', 'inbound')},
        ),
    ]
