# Generated by Django 5.2.14 on 2026-08-18 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0022_add_routestop_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='duty',
            name='no_run_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='duty',
            name='no_run_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalduty',
            name='no_run_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalduty',
            name='no_run_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
