# Generated by Django 5.2.3 on 2025-07-11 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='admin_only',
            field=models.BooleanField(default=False, help_text='Only admins can reply to this thread'),
        ),
        migrations.AddField(
            model_name='thread',
            name='locked',
            field=models.BooleanField(default=False, help_text='Lock this thread to prevent further replies'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='Markdown supported'),
        ),
    ]
