# Generated by Django 5.2.3 on 2025-07-11 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_thread_admin_only_thread_locked_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='discord_channel_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
