# Generated by Django 5.2.3 on 2025-07-23 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_thread_discord_channel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(help_text='Username of the post author', max_length=255),
        ),
    ]
