# Generated by Django 5.2.3 on 2025-07-24 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='message_limit',
            field=models.IntegerField(default=1000, help_text='Maximum number of messages allowed in this thread before it deletes the oldest messages'),
        ),
    ]
