# Generated by Django 5.2.3 on 2025-07-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_thread_message_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='message_limit',
            field=models.IntegerField(default=5000, help_text='Maximum number of messages allowed in this thread before it deletes the oldest messages'),
        ),
    ]
