# Generated by Django 5.2.3 on 2025-07-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_alter_thread_message_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='message_limit',
            field=models.IntegerField(default=0, help_text='0 for no limit else maximum number of messages allowed in this thread before it deletes the oldest messages'),
        ),
    ]
