# Generated by Django 5.2.3 on 2025-07-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_alter_thread_message_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='pinned',
            field=models.BooleanField(default=False, help_text='Pin this thread to the top of the forum'),
        ),
    ]
