# Generated by Django 5.2.3 on 2025-07-29 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_thread_pinned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='created_by',
            field=models.CharField(help_text='Username of the post author', max_length=255),
        ),
    ]
