# Generated by Django 5.2.3 on 2025-08-13 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_forum_thread_discord_forum_id_thread_forum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='discord_forum_id',
        ),
    ]
    