# Generated by Django 5.2.3 on 2025-08-13 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_forum_thread_discord_forum_id_thread_forum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='discord_forum_id',
        ),
        migrations.AddField(
            model_name='forum',
            name='discord_forum_id',
            field=models.CharField(default=1, help_text='Discord Forum Channel ID', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
