# Generated by Django 5.2.3 on 2025-10-24 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannedword',
            name='insta_ban',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalbannedword',
            name='insta_ban',
            field=models.BooleanField(default=False),
        ),
    ]

