# Generated by Django 5.2.14 on 2026-06-08 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_bannedword_insta_ban_historicalbannedword_insta_ban'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannedword',
            name='ban_group_name',
            field=models.BooleanField(default=True, verbose_name='Group name ban'),
        ),
        migrations.AddField(
            model_name='bannedword',
            name='ban_operator_name',
            field=models.BooleanField(default=True, verbose_name='Operator name ban'),
        ),
        migrations.AddField(
            model_name='bannedword',
            name='ban_search',
            field=models.BooleanField(default=True, verbose_name='Search ban'),
        ),
        migrations.AddField(
            model_name='bannedword',
            name='ban_username',
            field=models.BooleanField(default=True, verbose_name='Username ban'),
        ),
        migrations.AddField(
            model_name='historicalbannedword',
            name='ban_group_name',
            field=models.BooleanField(default=True, verbose_name='Group name ban'),
        ),
        migrations.AddField(
            model_name='historicalbannedword',
            name='ban_operator_name',
            field=models.BooleanField(default=True, verbose_name='Operator name ban'),
        ),
        migrations.AddField(
            model_name='historicalbannedword',
            name='ban_search',
            field=models.BooleanField(default=True, verbose_name='Search ban'),
        ),
        migrations.AddField(
            model_name='historicalbannedword',
            name='ban_username',
            field=models.BooleanField(default=True, verbose_name='Username ban'),
        ),
    ]
