# Generated by Django 5.2.3 on 2025-06-18 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyupdate',
            name='routes',
            field=models.ManyToManyField(blank=True, related_name='company_updates', to='routes.route'),
        ),
    ]
