# Generated by Django 5.2.3 on 2025-06-18 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_companyupdate_routes'),
        ('main', '0006_alter_google_ad_ad_id_alter_google_ad_ad_place_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='region',
        ),
        migrations.AlterField(
            model_name='mbtoperator',
            name='region',
            field=models.ManyToManyField(related_name='operators', to='main.region'),
        ),
    ]
