# Generated by Django 5.2.3 on 2025-07-08 12:17

import fleet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_companyupdate_routes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbtoperator',
            name='operator_details',
            field=models.JSONField(blank=True, default=fleet.models.default_operator_details, null=True),
        ),
    ]
