# Generated by Django 5.2.3 on 2025-06-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_delete_region_alter_mbtoperator_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleet',
            name='length',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
