# Generated by Django 5.2.3 on 2025-07-12 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_alter_mbtoperator_operator_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='mapTileSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('tile_url', models.CharField(max_length=255)),
                ('attribution', models.CharField(blank=True, max_length=255, null=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Map Tile Sets',
            },
        ),
    ]
