# Generated by Django 5.2.3 on 2025-07-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_alter_fleet_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleet',
            name='depot',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
