# Generated by Django 5.2.3 on 2025-07-12 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0005_maptileset'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ticket',
        ),
    ]
