# Generated by Django 5.2.3 on 2025-07-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0006_alter_group_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatortype',
            name='published',
            field=models.BooleanField(default=False, help_text='Mark this operator type as published to be used in the system.'),
        ),
    ]
