# Generated by Django 5.2.3 on 2025-07-12 21:32

import django.db.models.deletion
import fleet.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0006_delete_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ticket_name', models.CharField(max_length=50)),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ticket_details', models.TextField(blank=True)),
                ('zone', models.CharField(blank=True, help_text="Zone for the ticket (e.g., 'Zone 1', 'Zone A').", max_length=50)),
                ('valid_for_days', models.PositiveIntegerField(blank=True, null=True)),
                ('single_use', models.BooleanField(default=False, help_text='If true, this ticket can only be used once.')),
                ('name_on_ticketer', models.CharField(blank=True, help_text='Name to be displayed on the ticketer for this ticket.', max_length=50)),
                ('colour_on_ticketer', fleet.fields.ColourField(blank=True, help_text='Colour of the ticket in hex format (e.g., #FF5733).', max_length=7)),
                ('ticket_category', models.CharField(blank=True, help_text="Category of the ticket (e.g., 'Adult', 'Child', 'Senior').", max_length=100)),
                ('hidden_on_ticketer', models.BooleanField(default=False, help_text='If true, this ticket will not be displayed on the ticketer.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_operator', to='fleet.mbtoperator')),
            ],
        ),
    ]
