# Generated by Django 5.2.3 on 2025-07-13 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0007_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='mbtoperator',
            name='mapTile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operators', to='fleet.maptileset'),
        ),
    ]
