# Generated by Django 5.2.3 on 2025-07-13 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0008_mbtoperator_maptile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mbtoperator',
            old_name='mapTile',
            new_name='map_tile',
        ),
    ]
