# Generated by Django 5.2.3 on 2025-07-13 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0009_rename_maptile_mbtoperator_map_tile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mbtoperator',
            old_name='map_tile',
            new_name='mapTile',
        ),
    ]
