# Generated by Django 5.2.3 on 2025-07-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0010_rename_map_tile_mbtoperator_maptile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbtoperator',
            name='operator_name',
            field=models.CharField(help_text="Name of the operator, e.g., 'Example Bus Company'", max_length=50, unique=True),
        ),
    ]
