# Generated by Django 5.2.3 on 2025-07-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0011_alter_mbtoperator_operator_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbtoperator',
            name='operator_code',
            field=models.CharField(unique=True),
        ),
    ]
