# Generated by Django 5.2.3 on 2025-07-19 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0012_alter_mbtoperator_operator_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicletype',
            name='type_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
