# Generated by Django 5.2.3 on 2025-07-20 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0013_alter_vehicletype_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleet',
            name='fleet_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
