# Generated by Django 5.2.3 on 2025-07-20 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0014_alter_fleet_fleet_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleet',
            name='fleet_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='prev_reg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='reg',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
