# Generated by Django 5.2.3 on 2025-07-20 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0015_alter_fleet_fleet_number_alter_fleet_prev_reg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleet',
            name='last_tracked_route',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
