# Generated by Django 5.2.3 on 2025-07-20 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0016_alter_fleet_last_tracked_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleet',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
