# Generated by Django 5.2.3 on 2025-07-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0017_alter_fleet_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleet',
            name='branding',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='colour',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='depot',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='fleet_number',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='last_tracked_route',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='length',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='name',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='reg',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='type_details',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name='helperperm',
            name='perm_name',
            field=models.CharField(help_text='Name of the permission', unique=True),
        ),
        migrations.AlterField(
            model_name='mbtoperator',
            name='operator_name',
            field=models.CharField(help_text="Name of the operator, e.g., 'Example Bus Company'", unique=True),
        ),
        migrations.AlterField(
            model_name='operatortype',
            name='operator_type_name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='organisation_name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='reservedoperatorname',
            name='operator_name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='name_on_ticketer',
            field=models.CharField(blank=True, help_text='Name to be displayed on the ticketer for this ticket.'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='zone',
            field=models.CharField(blank=True, help_text="Zone for the ticket (e.g., 'Zone 1', 'Zone A')."),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='fuel',
            field=models.CharField(default='Diesel'),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='type',
            field=models.CharField(default='Bus'),
        ),
    ]
