# Generated by Django 5.2.3 on 2025-07-31 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0018_alter_fleet_branding_alter_fleet_colour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicletype',
            name='hidden',
            field=models.BooleanField(default=False, help_text='If true, this type will not be displayed in the UI.'),
        ),
    ]
