# Generated by Django 5.2.3 on 2025-08-01 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0019_vehicletype_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liverie',
            name='colour',
            field=models.CharField(help_text='For the most simplified version of the livery', max_length=100),
        ),
        migrations.AlterField(
            model_name='liverie',
            name='stroke_colour',
            field=models.CharField(blank=True, help_text='Use sparingly, often looks shit', max_length=100),
        ),
        migrations.AlterField(
            model_name='liverie',
            name='text_colour',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
