# Generated by Django 5.2.3 on 2025-08-06 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0020_alter_liverie_colour_alter_liverie_stroke_colour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleet',
            name='branding',
            field=models.CharField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='colour',
            field=models.CharField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='depot',
            field=models.CharField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='features',
            field=models.JSONField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='fleet_number',
            field=models.CharField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='for_sale',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='id',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='in_service',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='last_tracked_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='last_tracked_route',
            field=models.CharField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='length',
            field=models.CharField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='name',
            field=models.CharField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='notes',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='on_load',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='open_top',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='preserved',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='prev_reg',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='reg',
            field=models.CharField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='liverie',
            name='id',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
    ]
