# Generated by Django 5.2.3 on 2025-08-06 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0021_alter_fleet_branding_alter_fleet_colour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleet',
            name='fleet_number_sort',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
