# Generated by Django 5.2.3 on 2025-08-19 06:07

import fleet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0022_fleet_fleet_number_sort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleet',
            name='operator',
            field=models.ForeignKey(blank=True, on_delete=models.SET(fleet.models.default_operator_id), related_name='fleet_operator', to='fleet.mbtoperator'),
        ),
    ]
