# Generated by Django 5.2.3 on 2025-08-23 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0023_alter_fleet_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleet',
            name='advanced_details',
            field=models.JSONField(blank=True, db_index=True, null=True),
        ),
    ]
