# Generated by Django 5.2.3 on 2025-08-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0024_fleet_advanced_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='mbtoperator',
            name='operator_slug',
            field=models.SlugField(blank=True, unique=False),
        ),
    ]
