# Generated by Django 5.2.3 on 2025-08-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0025_mbtoperator_operator_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbtoperator',
            name='operator_slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
