# Generated by Django 5.2.3 on 2025-08-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0026_alter_mbtoperator_operator_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleet',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
