# Generated by Django 5.2.3 on 2025-08-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0027_fleet_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='mbtoperator',
            name='vehicles_for_sale',
            field=models.IntegerField(default=0),
        ),
    ]
