# Generated by Django 5.2.3 on 2025-09-05 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0028_mbtoperator_vehicles_for_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbtoperator',
            name='operator_slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
