# Generated by Django 5.2.3 on 2025-10-12 07:02

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0029_alter_mbtoperator_operator_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Historicalfleet',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('in_service', models.BooleanField(db_index=True, default=True)),
                ('for_sale', models.BooleanField(db_index=True, default=False)),
                ('preserved', models.BooleanField(db_index=True, default=False)),
                ('on_load', models.BooleanField(db_index=True, default=False)),
                ('open_top', models.BooleanField(db_index=True, default=False)),
                ('fleet_number', models.CharField(blank=True, db_index=True, null=True)),
                ('fleet_number_sort', models.CharField(blank=True, max_length=100, null=True)),
                ('reg', models.CharField(blank=True, db_index=True, null=True)),
                ('prev_reg', models.TextField(blank=True, db_index=True, null=True)),
                ('colour', models.CharField(blank=True, db_index=True)),
                ('type_details', models.CharField(blank=True)),
                ('last_tracked_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_tracked_route', models.CharField(blank=True, db_index=True, null=True)),
                ('branding', models.CharField(blank=True, db_index=True)),
                ('depot', models.CharField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(blank=True, db_index=True)),
                ('length', models.CharField(blank=True, db_index=True, null=True)),
                ('features', models.JSONField(blank=True, db_index=True)),
                ('notes', models.TextField(blank=True, db_index=True, null=True)),
                ('advanced_details', models.JSONField(blank=True, db_index=True, null=True)),
                ('summary', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('livery', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fleet.liverie')),
                ('loan_operator', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fleet.mbtoperator')),
                ('operator', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fleet.mbtoperator')),
                ('vehicleType', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fleet.vehicletype')),
            ],
            options={
                'verbose_name': 'historical fleet',
                'verbose_name_plural': 'historical fleets',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
