# Generated by Django 5.2.3 on 2025-10-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0031_historicalcompanyupdate_historicalfleetchange_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmbtoperator',
            name='public_notes',
            field=models.TextField(blank=True, help_text='Show on the operator pages to explain the company.'),
        ),
        migrations.AddField(
            model_name='historicalmbtoperator',
            name='verified',
            field=models.BooleanField(default=False, help_text='Mark this operator as verified to show a verified badge on the operator page.'),
        ),
        migrations.AddField(
            model_name='mbtoperator',
            name='public_notes',
            field=models.TextField(blank=True, help_text='Show on the operator pages to explain the company.'),
        ),
        migrations.AddField(
            model_name='mbtoperator',
            name='verified',
            field=models.BooleanField(default=False, help_text='Mark this operator as verified to show a verified badge on the operator page.'),
        ),
    ]
