# Generated by Django 5.2.3 on 2025-10-24 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0032_historicalmbtoperator_public_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalliverie',
            name='declined',
            field=models.BooleanField(default=False, help_text='Tick to mark this livery as declined and not approved for use'),
        ),
        migrations.AddField(
            model_name='liverie',
            name='declined',
            field=models.BooleanField(default=False, help_text='Tick to mark this livery as declined and not approved for use'),
        ),
    ]
