# Generated by Django 5.2.12 on 2026-05-22 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0044_update_default_fluffynet_map_tiles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='favouriteLivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('livery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourited_by', to='fleet.liverie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_liveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Favourite liveries',
                'ordering': ('livery__name',),
                'unique_together': {('user', 'livery')},
            },
        ),
        migrations.CreateModel(
            name='favouriteVehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_vehicle_types', to=settings.AUTH_USER_MODEL)),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourited_by', to='fleet.vehicletype')),
            ],
            options={
                'verbose_name_plural': 'Favourite vehicle types',
                'ordering': ('vehicle_type__type_name',),
                'unique_together': {('user', 'vehicle_type')},
            },
        ),
    ]
