# Generated by Django 5.2.12 on 2026-05-29 21:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0046_favouriteoperator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='maptileset',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, help_text='Leave empty to make this map tile set available to everyone. Add users to lock it to them.', related_name='allowed_map_tile_sets', to=settings.AUTH_USER_MODEL),
        ),
    ]
