# Generated by Django 5.2.12 on 2026-05-29 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0047_maptileset_allowed_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmaptileset',
            name='pro_access',
            field=models.BooleanField(default=False, help_text='Allow any user with an active Pro subscription to use this map tile set.'),
        ),
        migrations.AddField(
            model_name='maptileset',
            name='pro_access',
            field=models.BooleanField(default=False, help_text='Allow any user with an active Pro subscription to use this map tile set.'),
        ),
    ]
