# Generated by Django 5.2.12 on 2026-05-31 00:56

from django.db import migrations, models


def set_default_tracking_trail_colours(apps, schema_editor):
    map_tile_set = apps.get_model('fleet', 'mapTileSet')
    dark_words = ('dark', 'night', 'black', 'nocturne', 'satellite')

    for tile in map_tile_set.objects.all():
        name = (tile.name or '').lower()
        tile_url = (tile.tile_url or '').lower()
        if tile.tracking_trail_colour:
            continue
        tile.tracking_trail_colour = (
            '#f5f5f5'
            if any(word in name or word in tile_url for word in dark_words)
            else '#111111'
        )
        tile.save(update_fields=['tracking_trail_colour'])


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0048_historicalmaptileset_pro_access_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmaptileset',
            name='tracking_trail_colour',
            field=models.CharField(blank=True, default='', help_text='Colour used for tracking trail arrows/lines on maps using this tile theme.', max_length=32),
        ),
        migrations.AddField(
            model_name='maptileset',
            name='tracking_trail_colour',
            field=models.CharField(blank=True, default='', help_text='Colour used for tracking trail arrows/lines on maps using this tile theme.', max_length=32),
        ),
        migrations.RunPython(set_default_tracking_trail_colours, migrations.RunPython.noop),
    ]
