# Generated by Django 5.2.14 on 2026-06-03 20:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0049_historicalmaptileset_tracking_trail_colour_and_more'),
        ('routes', '0019_historicaltimetableentry_active_and_more'),
        ('tracking', '0011_blockvehicleswap'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fleet',
            options={'verbose_name_plural': 'fleet'},
        ),
        migrations.AlterModelOptions(
            name='historicalfleet',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical fleet', 'verbose_name_plural': 'historical fleet'},
        ),
        migrations.AlterField(
            model_name='fleet',
            name='fleet_number_sort',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfleet',
            name='fleet_number_sort',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='fleet',
            index=models.Index(fields=['operator', 'in_service'], name='fleet_op_in_svc_idx'),
        ),
        migrations.AddIndex(
            model_name='fleet',
            index=models.Index(fields=['loan_operator', 'in_service'], name='fleet_loan_op_in_svc_idx'),
        ),
        migrations.AddIndex(
            model_name='fleet',
            index=models.Index(fields=['fleet_number_sort'], name='fleet_fn_sort_idx'),
        ),
    ]
