# Generated by Django 5.2.12 on 2026-06-01 21:17

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0049_historicalmaptileset_tracking_trail_colour_and_more'),
        ('routes', '0019_historicaltimetableentry_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalDepot',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('double_decker', models.BooleanField(default=True)),
                ('single_decker', models.BooleanField(default=True)),
                ('minibuses', models.BooleanField(default=True)),
                ('custom_vehicle_options', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fleet.mbtoperator')),
            ],
            options={
                'verbose_name': 'historical depot',
                'verbose_name_plural': 'historical depots',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('double_decker', models.BooleanField(default=True)),
                ('single_decker', models.BooleanField(default=True)),
                ('minibuses', models.BooleanField(default=True)),
                ('custom_vehicle_options', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depots', to='fleet.mbtoperator')),
                ('running_board_categories', models.ManyToManyField(blank=True, db_constraint=False, limit_choices_to={'board_type': 'running-boards'}, related_name='depots', to='routes.board_category')),
            ],
            options={
                'ordering': ('name',),
                'constraints': [models.UniqueConstraint(fields=('operator', 'name'), name='unique_depot_name_per_operator')],
            },
        ),
    ]
