# Generated by Django 5.2.14 on 2026-06-08 01:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0050_alter_fleet_options_alter_historicalfleet_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservedoperatorname',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, help_text='Extra users allowed to use this reserved operator name. The owner is always allowed.', related_name='allowed_reserved_operator_names', to=settings.AUTH_USER_MODEL),
        ),
    ]
