# Generated by Django 5.2.12 on 2026-06-01 21:27

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


def seed_category_vehicle_options(apps, schema_editor):
    Depot = apps.get_model('fleet', 'Depot')
    DepotBoardCategoryVehicleOptions = apps.get_model('fleet', 'DepotBoardCategoryVehicleOptions')
    through_model = Depot.running_board_categories.through

    for depot in Depot.objects.all():
        vehicle_options = []
        if depot.double_decker:
            vehicle_options.append("Double Decker")
        if depot.single_decker:
            vehicle_options.append("Single Decker")
        if depot.minibuses:
            vehicle_options.append("Minibuses")
        vehicle_options.extend(depot.custom_vehicle_options or [])

        category_ids = through_model.objects.filter(depot_id=depot.id).values_list('board_category_id', flat=True)
        for category_id in category_ids:
            DepotBoardCategoryVehicleOptions.objects.get_or_create(
                depot_id=depot.id,
                category_id=category_id,
                defaults={'vehicle_options': vehicle_options},
            )


def unseed_category_vehicle_options(apps, schema_editor):
    DepotBoardCategoryVehicleOptions = apps.get_model('fleet', 'DepotBoardCategoryVehicleOptions')
    DepotBoardCategoryVehicleOptions.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0050_historicaldepot_depot'),
        ('routes', '0019_historicaltimetableentry_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalDepotBoardCategoryVehicleOptions',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('vehicle_options', models.JSONField(blank=True, default=list)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('category', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'board_type': 'running-boards'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='routes.board_category')),
                ('depot', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fleet.depot')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical depot board category vehicle options',
                'verbose_name_plural': 'historical depot board category vehicle optionss',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='DepotBoardCategoryVehicleOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_options', models.JSONField(blank=True, default=list)),
                ('category', models.ForeignKey(db_constraint=False, limit_choices_to={'board_type': 'running-boards'}, on_delete=django.db.models.deletion.CASCADE, related_name='depot_vehicle_options', to='routes.board_category')),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_vehicle_options', to='fleet.depot')),
            ],
            options={
                'ordering': ('category__name',),
                'constraints': [models.UniqueConstraint(fields=('depot', 'category'), name='unique_depot_category_vehicle_options')],
            },
        ),
        migrations.RunPython(seed_category_vehicle_options, unseed_category_vehicle_options),
    ]
