# Generated by Django 5.2.14 on 2026-06-10 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0051_reservedoperatorname_allowed_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleet',
            name='fleet_number',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='fleet_number_sort',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfleet',
            name='fleet_number',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfleet',
            name='fleet_number_sort',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
