# Generated by Django 5.2.14 on 2026-07-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0052_alter_fleet_fleet_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleet',
            name='last_trip_datetime',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fleet',
            name='last_trip_route_num',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalfleet',
            name='last_trip_datetime',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalfleet',
            name='last_trip_route_num',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
