# Generated by Django 5.2.14 on 2026-07-27 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0053_fleet_last_trip_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmbtoperator',
            name='show_feature_icons',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mbtoperator',
            name='show_feature_icons',
            field=models.BooleanField(default=True),
        ),
    ]
