# Generated by Django 5.2.14 on 2026-07-27 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0054_historicalmbtoperator_show_feature_icons_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmbtoperator',
            name='show_feature_icons',
        ),
        migrations.RemoveField(
            model_name='mbtoperator',
            name='show_feature_icons',
        ),
    ]
