# Generated by Django 5.2.14 on 2026-07-27 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0055_remove_historicalmbtoperator_show_feature_icons_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvehicletype',
            name='evidence',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='evidence',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vehicletypechangerequest',
            name='evidence',
            field=models.TextField(blank=True),
        ),
    ]
