# Generated by Django 5.2.14 on 2026-07-31 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0056_historicalvehicletype_evidence_vehicletype_evidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvehicletype',
            name='door_amount',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='historicalvehicletype',
            name='engine',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='historicalvehicletype',
            name='gearbox',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='door_amount',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='engine',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='gearbox',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
