# Generated by Django 5.2.14 on 2026-07-31 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0057_historicalvehicletype_door_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvehicletype',
            name='engine',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalvehicletype',
            name='gearbox',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='engine',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='gearbox',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
