# Generated by Django 5.2.14 on 2026-07-31 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0058_engine_gearbox_field_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleet',
            name='door_amount',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='fleet',
            name='engine',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='fleet',
            name='gearbox',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='historicalfleet',
            name='door_amount',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='historicalfleet',
            name='engine',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='historicalfleet',
            name='gearbox',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
