# Generated by Django 5.2.14 on 2026-08-19 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0060_historicaloperatortransferrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleet',
            name='loan_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fleet',
            name='loan_until',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalfleet',
            name='loan_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalfleet',
            name='loan_until',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
