# Generated by Django 5.2.14 on 2026-08-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0061_fleet_loan_snapshot_fleet_loan_until_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='operatortransferrequest',
            constraint=models.UniqueConstraint(
                condition=models.Q(('status', 'pending')),
                fields=('operator',),
                name='unique_pending_transfer_per_operator',
            ),
        ),
    ]
