# Generated by Django 5.2.14 on 2026-08-21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0062_operatortransferrequest_unique_pending_operator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbandonedBusOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_year', models.PositiveSmallIntegerField()),
                ('amount', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('destination_operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_abandoned_bus_orders', to='fleet.mbtoperator')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abandoned_bus_orders', to=settings.AUTH_USER_MODEL)),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abandoned_bus_orders', to='fleet.vehicletype')),
            ],
            options={'ordering': ['-created_at']},
        ),
    ]
