# Generated by Django 5.2.14 on 2026-08-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0063_abandonedbusorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abandonedbusorder',
            name='registration_year',
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text='The selected calendar year, or blank when any year was selected.',
                null=True,
            ),
        ),
    ]
