# Generated by Django 5.2.14 on 2026-08-24 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0064_alter_abandonedbusorder_registration_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleet',
            name='vor',
            field=models.BooleanField(db_index=True, default=False, help_text='Vehicle Off Road - cannot be logged.'),
        ),
        migrations.AddField(
            model_name='historicalfleet',
            name='vor',
            field=models.BooleanField(db_index=True, default=False, help_text='Vehicle Off Road - cannot be logged.'),
        ),
    ]
