# Generated by Django 5.2.14 on 2026-08-26 18:12

import django.db.models.deletion
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0066_historicalvehicletransferrequest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalvehicleTransferRequest_vehicles',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('m2m_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('fleet', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fleet.fleet')),
                ('history', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='fleet.historicalvehicletransferrequest')),
                ('vehicletransferrequest', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fleet.vehicletransferrequest')),
            ],
            options={
                'verbose_name': 'HistoricalvehicleTransferRequest_vehicles',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
