# Generated by Django 5.2.14 on 2026-08-26 18:25

import fleet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0067_add_vehicletransferrequest_vehicles_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvehicletransferrequest',
            name='vehicles_in_service',
            field=models.JSONField(blank=True, default=dict, help_text='Prior in_service per vehicle id while pending.'),
        ),
        migrations.AddField(
            model_name='vehicletransferrequest',
            name='vehicles_in_service',
            field=models.JSONField(blank=True, default=dict, help_text='Prior in_service per vehicle id while pending.'),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='colour',
            field=models.CharField(blank=True, db_index=True, validators=[fleet.models.validate_strict_colour]),
        ),
        migrations.AlterField(
            model_name='historicalfleet',
            name='colour',
            field=models.CharField(blank=True, db_index=True, validators=[fleet.models.validate_strict_colour]),
        ),
        migrations.AlterField(
            model_name='historicalliverie',
            name='colour',
            field=models.CharField(help_text='For the most simplified version of the livery', max_length=100, validators=[fleet.models.validate_strict_colour]),
        ),
        migrations.AlterField(
            model_name='liverie',
            name='colour',
            field=models.CharField(help_text='For the most simplified version of the livery', max_length=100, validators=[fleet.models.validate_strict_colour]),
        ),
    ]
