# Generated by Django 5.2.14 on 2026-09-12 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0068_transfer_request_store_in_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvehicletransferrequest',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, help_text='Optional date/time the sender scheduled this transfer for. Informational only; the request still needs accepting.', null=True),
        ),
        migrations.AddField(
            model_name='vehicletransferrequest',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, help_text='Optional date/time the sender scheduled this transfer for. Informational only; the request still needs accepting.', null=True),
        ),
    ]
