# Generated by Django 5.2.14 on 2026-09-12 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0069_historicalvehicletransferrequest_scheduled_for_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvehicletransferrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('cancelled', 'Cancelled'), ('scheduled', 'Scheduled')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='vehicletransferrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('cancelled', 'Cancelled'), ('scheduled', 'Scheduled')], default='pending', max_length=10),
        ),
    ]
