# Generated by Django 5.2.14 on 2026-09-14 12:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0070_alter_historicalvehicletransferrequest_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='vehicletransferrequest',
            index=models.Index(fields=['status', 'scheduled_for'], name='fleet_vtr_status_sched_idx'),
        ),
    ]
