# Generated by Django 5.2.3 on 2025-06-17 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=100, unique=True)),
                ('region_code', models.CharField(max_length=3, unique=True)),
                ('region_country', models.CharField(default='England', max_length=100)),
                ('in_the', models.BooleanField(default=False)),
            ],
        ),
    ]
