# Generated by Django 5.2.3 on 2025-07-22 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_importjob'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImportJob',
        ),
    ]
