# Generated by Django 5.2.3 on 2025-06-17 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='theme',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('theme_name', models.CharField(blank=True, max_length=50, null=True)),
                ('css', models.FileField(help_text='Upload a CSS file. <a href="/media/themes/templateTheme.css" target="_blank">Download template</a>', upload_to='themes/')),
                ('main_colour', models.CharField(blank=True, max_length=50)),
                ('dark_theme', models.BooleanField(default=False)),
                ('weight', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='theme_id',
        ),
        migrations.AddField(
            model_name='customuser',
            name='theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.theme'),
        ),
    ]
