# Generated by Django 5.2.3 on 2025-06-18 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_theme_remove_customuser_theme_id_customuser_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_name', models.CharField(max_length=100)),
                ('ad_img', models.ImageField(upload_to='images/')),
                ('ad_link', models.TextField()),
                ('ad_live', models.BooleanField(default=False)),
            ],
        ),
    ]
