# Generated by Django 5.2.3 on 2025-07-22 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_importjob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importjob',
            name='user',
        ),
    ]
