# Generated by Django 5.2.3 on 2025-06-18 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_ad'),
    ]

    operations = [
        migrations.CreateModel(
            name='google_ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_type', models.CharField(choices=[('article', 'Article'), ('banner', 'Banner')], max_length=50)),
                ('ad_id', models.CharField(help_text='Google Ad ID (e.g., 6635106786)', max_length=100, unique=True)),
                ('ad_place_id', models.CharField(help_text='MBT AD Box ID (e.g., body-ad-1)', max_length=100, unique=True)),
            ],
        ),
    ]
