# Generated by Django 5.2.3 on 2025-06-18 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_google_ad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='google_ad',
            name='ad_id',
            field=models.CharField(help_text='Google Ad ID (e.g., 6635106786)', max_length=100),
        ),
        migrations.AlterField(
            model_name='google_ad',
            name='ad_place_id',
            field=models.CharField(help_text='MBT AD Box ID (e.g., body-ad-1)', max_length=100),
        ),
    ]
