# Generated by Django 5.2.3 on 2025-07-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_importjob_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='importjob',
            name='username_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
