# Generated by Django 5.2.3 on 2025-06-18 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_featuretoggle_serviceupdate_loginiphashlog_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('Bug', 'Bug'), ('User', 'User')], max_length=10)),
                ('details', models.TextField(help_text='Describe what happened')),
                ('context', models.TextField(blank=True, help_text='Add any links, vehicle IDs, or extra context')),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='reports/screenshots/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
