# Generated by Django 5.2.3 on 2025-07-24 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_customuser_stripe_subscription_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='discord_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
