# Generated by Django 5.2.3 on 2025-06-18 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='banner',
            field=models.ImageField(blank=True, default='images/default_banner.png', null=True, upload_to='images/profile_banners/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='pfp',
            field=models.ImageField(blank=True, default='images/default_profile_pic.png', null=True, upload_to='images/profile_pics/'),
        ),
    ]
