# Generated by Django 5.2.3 on 2025-06-19 19:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_customuser_banner_alter_customuser_pfp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuretoggle',
            name='coming_soon_percent',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
