# Generated by Django 5.2.3 on 2025-06-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_featuretoggle_coming_soon_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='css',
            field=models.FileField(help_text='Upload a CSS file. <a href="/static/themes/templateTheme.css" target="_blank">Download template</a>', upload_to='themes/'),
        ),
    ]
