# Generated by Django 5.2.3 on 2025-08-19 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_userkeys'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='buses_brought_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_bus_purchase',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
