# Generated by Django 5.2.3 on 2025-06-27 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_bannedips_delete_loginiphashlog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='serviceUpdate',
            new_name='siteUpdate',
        ),
    ]
