# Generated by Django 5.2.3 on 2025-08-22 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_customuser_buses_brought_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='mbt_admin_perms',
        ),
        migrations.CreateModel(
            name='MBTTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('permissions', models.ManyToManyField(blank=True, related_name='teams', to='main.mbtadminpermission')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='mbt_team',
            field=models.ForeignKey(blank=True, help_text='Team the user belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='main.mbtteam'),
        ),
    ]
