# Generated by Django 5.2.3 on 2025-08-23 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_customuser_mbt_admin_perms_mbtteam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Internal notes for admins only', null=True),
        ),
    ]
