# Generated by Django 5.2.3 on 2025-07-02 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_serviceupdate_siteupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='ad_img_overide',
            field=models.URLField(blank=True, help_text='Override image URL for the ad', null=True),
        ),
    ]
