# Generated by Django 5.2.3 on 2025-07-03 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_ad_ad_img_overide'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reg_background',
            field=models.BooleanField(default=True),
        ),
    ]
