# Generated by Django 5.2.3 on 2025-08-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_communityimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('Bug', 'Bug'), ('User', 'User'), ('Image', 'Image')], max_length=10),
        ),
    ]
