# Generated by Django 5.2.3 on 2025-07-04 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_customuser_reg_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuretoggle',
            name='super_user_only',
            field=models.BooleanField(default=False, help_text='Only superusers can access this feature'),
        ),
    ]
