# Generated by Django 5.2.3 on 2025-08-30 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_report_report_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='forum_banned',
            field=models.BooleanField(default=False),
        ),
    ]
