# Generated by Django 5.2.3 on 2025-09-06 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_customuser_forum_banned'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='messaging_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ticket_banned',
            field=models.BooleanField(default=False),
        ),
    ]
