# Generated by Django 5.2.3 on 2025-09-06 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_customuser_messaging_banned_customuser_ticket_banned'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='wiki_edit_banned',
            field=models.BooleanField(default=False),
        ),
    ]
