# Generated by Django 5.2.3 on 2025-10-06 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_customuser_wiki_edit_banned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='css',
            field=models.FileField(help_text='Upload a CSS file. <a href="/static/themes/templateTheme.css" target="_blank">Download template</a>', upload_to='static/themes/'),
        ),
    ]
