# Generated by Django 5.2.3 on 2025-10-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_historicalad_historicalbadge_historicalbannedips_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsiteupdate',
            name='warning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='siteupdate',
            name='warning',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicalsiteupdate',
            name='live',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='siteupdate',
            name='live',
            field=models.BooleanField(default=True),
        ),
    ]
