# Generated by Django 5.2.3 on 2025-10-24 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_bannedword_whitelistedword_historicalbannedword_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bannedWord',
        ),
        migrations.RemoveField(
            model_name='historicalbannedword',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalwhitelistedword',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='whitelistedWord',
        ),
        migrations.DeleteModel(
            name='HistoricalbannedWord',
        ),
        migrations.DeleteModel(
            name='HistoricalwhitelistedWord',
        ),
    ]
