# Generated by Django 5.2.3 on 2025-10-24 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_delete_bannedword_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcustomuser',
            name='last_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
