# Generated by Django 5.2.3 on 2025-10-30 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_customuser_last_ip_historicalcustomuser_last_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='oidc_sub',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='historicalcustomuser',
            name='oidc_sub',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
