# Generated by Django 5.2.14 on 2026-05-11 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_alter_deviceusage_first_seen_and_more'),
        ('main', '0047_suspicioussignupalert'),
    ]

    operations = [
    ]
