# Generated by Django 5.2.12 on 2026-05-28 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_readd_creating_games_ban_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='discord_avatar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='discord_global_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='discord_id',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='historicalcustomuser',
            name='discord_avatar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalcustomuser',
            name='discord_global_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalcustomuser',
            name='discord_id',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
    ]
