# Generated by Django 5.2.14 on 2026-07-25 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_alter_customuser_last_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='fleet_icons',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalcustomuser',
            name='fleet_icons',
            field=models.BooleanField(default=True),
        ),
    ]
