# Generated by Django 5.2.3 on 2025-08-13 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat_type',
            field=models.CharField(choices=[('direct', 'Direct Message'), ('group_private', 'Group')], max_length=20),
        ),
    ]
