# Generated by Django 5.2 on 2025-04-18 13:36

import django.db.models.deletion
import routes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mybustimes', '0016_delete_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='dayType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='route',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('route_num', models.CharField(blank=True, max_length=50, null=True)),
                ('route_name', models.CharField(blank=True, max_length=4, null=True)),
                ('route_details', models.JSONField(blank=True, default=routes.models.default_route_details)),
                ('inboud_destination', models.CharField(blank=True, max_length=100, null=True)),
                ('outboud_destination', models.CharField(blank=True, max_length=100, null=True)),
                ('other_destination', models.JSONField(blank=True, null=True)),
                ('linked_route', models.ManyToManyField(blank=True, to='routes.route')),
                ('related_route', models.ManyToManyField(blank=True, to='routes.route')),
                ('route_operators', models.ManyToManyField(related_name='route_other_operators', to='mybustimes.mbtoperator')),
            ],
        ),
        migrations.CreateModel(
            name='timetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times', models.JSONField()),
                ('day_type', models.ManyToManyField(related_name='timetable_entries', to='routes.daytype')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.route')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.stop')),
            ],
        ),
    ]
