# Generated by Django 5.2 on 2025-04-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_stop_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='source',
            field=models.CharField(default='custom', max_length=20),
        ),
    ]
