# Generated by Django 5.2 on 2025-04-23 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_stop_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='service_update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('update_type', models.CharField(max_length=20)),
                ('update_details', models.JSONField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.route')),
            ],
        ),
    ]
