# Generated by Django 5.2 on 2025-04-23 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_service_update'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='service_update',
            new_name='serviceUpdate',
        ),
    ]
