# Generated by Django 5.2 on 2025-04-23 18:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0005_rename_service_update_serviceupdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceupdate',
            old_name='date',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='serviceupdate',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
