# Generated by Django 5.2 on 2025-04-23 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0006_rename_date_serviceupdate_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceupdate',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_updates', to='routes.route'),
        ),
    ]
