# Generated by Django 5.2 on 2025-04-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0007_alter_serviceupdate_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='route_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
