# Generated by Django 5.2 on 2025-04-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0008_alter_route_route_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceupdate',
            name='route',
        ),
        migrations.AddField(
            model_name='serviceupdate',
            name='effected_route',
            field=models.ManyToManyField(related_name='service_updates', to='routes.route'),
        ),
    ]
