# Generated by Django 5.2 on 2025-04-27 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0009_remove_serviceupdate_route_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceupdate',
            name='update_type',
        ),
    ]
