# Generated by Django 5.2.3 on 2025-06-18 08:53

import django.db.models.deletion
import tracking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0003_delete_region_alter_mbtoperator_region'),
        ('gameData', '0001_initial'),
        ('routes', '0002_duty_duty_operator_route_route_operators'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameTracking',
            fields=[
                ('tracking_id', models.AutoField(primary_key=True, serialize=False)),
                ('tracking_data', models.JSONField(default=tracking.models.default_tracking_data)),
                ('tracking_history_data', models.JSONField(default=tracking.models.default_tracking_history)),
                ('tracking_start_location', models.CharField(blank=True, max_length=255, null=True)),
                ('tracking_end_location', models.CharField(blank=True, max_length=255, null=True)),
                ('tracking_start_at', models.DateTimeField(blank=True, null=True)),
                ('tracking_end_at', models.DateTimeField(blank=True, null=True)),
                ('tracking_updated_at', models.DateTimeField(auto_now=True)),
                ('trip_ended', models.BooleanField(default=False)),
                ('tracking_game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gameData.game')),
                ('tracking_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.route')),
                ('tracking_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.fleet')),
            ],
        ),
    ]
