# Generated by Django 5.2.3 on 2025-06-25 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_alter_fleet_length'),
        ('gameData', '0001_initial'),
        ('routes', '0005_rename_inboud_destination_route_inbound_destination_and_more'),
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GameTracking',
            new_name='Trip',
        ),
    ]
