# Generated by Django 5.2.3 on 2025-07-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0018_alter_fleet_branding_alter_fleet_colour_and_more'),
        ('gameData', '0001_initial'),
        ('routes', '0008_alter_timetableentry_stop_times'),
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tracking',
            index=models.Index(fields=['trip_ended'], name='tracking_tr_trip_en_1a75f4_idx'),
        ),
        migrations.AddIndex(
            model_name='tracking',
            index=models.Index(fields=['tracking_start_at'], name='tracking_tr_trackin_c0c4fc_idx'),
        ),
        migrations.AddIndex(
            model_name='tracking',
            index=models.Index(fields=['tracking_vehicle'], name='tracking_tr_trackin_8383df_idx'),
        ),
        migrations.AddIndex(
            model_name='tracking',
            index=models.Index(fields=['tracking_route'], name='tracking_tr_trackin_f0867a_idx'),
        ),
    ]
