# Generated by Django 5.2.3 on 2025-06-25 13:16

import django.db.models.deletion
import tracking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_alter_fleet_length'),
        ('gameData', '0001_initial'),
        ('routes', '0005_rename_inboud_destination_route_inbound_destination_and_more'),
        ('tracking', '0002_rename_gametracking_trip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='tracking_end_at',
            new_name='trip_end_at',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='tracking_end_location',
            new_name='trip_end_location',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='tracking_id',
            new_name='trip_id',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='tracking_route',
            new_name='trip_route',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='tracking_start_at',
            new_name='trip_start_at',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='tracking_start_location',
            new_name='trip_start_location',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='tracking_updated_at',
            new_name='trip_updated_at',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='tracking_vehicle',
            new_name='trip_vehicle',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='tracking_data',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='tracking_game',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='tracking_history_data',
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('tracking_id', models.AutoField(primary_key=True, serialize=False)),
                ('tracking_data', models.JSONField(default=tracking.models.default_tracking_data)),
                ('tracking_history_data', models.JSONField(default=tracking.models.default_tracking_history)),
                ('tracking_start_location', models.CharField(blank=True, max_length=255, null=True)),
                ('tracking_end_location', models.CharField(blank=True, max_length=255, null=True)),
                ('tracking_start_at', models.DateTimeField(blank=True, null=True)),
                ('tracking_end_at', models.DateTimeField(blank=True, null=True)),
                ('tracking_updated_at', models.DateTimeField(auto_now=True)),
                ('trip_ended', models.BooleanField(default=False)),
                ('tracking_game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gameData.game')),
                ('tracking_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.route')),
                ('tracking_trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracking.trip')),
                ('tracking_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.fleet')),
            ],
        ),
    ]
