# Generated by Django 5.2.3 on 2025-07-30 16:59

import tracking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_tracking_tracking_tr_trip_en_1a75f4_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='tracking_data',
            field=models.JSONField(db_index=True, default=tracking.models.default_tracking_data),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='tracking_end_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='tracking_end_location',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='tracking_history_data',
            field=models.JSONField(db_index=True, default=tracking.models.default_tracking_history),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='tracking_id',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='tracking_start_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='tracking_start_location',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='tracking_updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='trip_ended',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_end_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_end_location',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_ended',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_id',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_route_num',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_start_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_start_location',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
