# Generated by Django 5.2.3 on 2025-08-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_alter_tracking_tracking_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='trip_missed',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
