# Generated by Django 5.2.3 on 2025-06-25 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_rename_tracking_end_at_trip_trip_end_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='trip_route_num',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
