# Generated by Django 5.2.3 on 2025-06-25 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0005_rename_inboud_destination_route_inbound_destination_and_more'),
        ('tracking', '0004_trip_trip_route_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='trip_route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='routes.route'),
        ),
    ]
