# Generated by Django 5.2.3 on 2025-08-25 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_trip_trip_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='trip_display_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
