# Generated by Django 5.2.3 on 2025-09-09 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0010_route_route_depot'),
        ('tracking', '0006_trip_trip_display_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='tracking_route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='routes.route'),
        ),
    ]
