# Generated by Django 5.2.3 on 2025-10-12 07:14

import django.db.models.deletion
import simple_history.models
import tracking.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0031_historicalcompanyupdate_historicalfleetchange_and_more'),
        ('gameData', '0003_historicalgame_historicalgame_tiles'),
        ('routes', '0012_historicaldaytype_historicalduty_historicaldutytrip_and_more'),
        ('tracking', '0007_alter_tracking_tracking_route'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTracking',
            fields=[
                ('tracking_id', models.IntegerField(blank=True, db_index=True)),
                ('tracking_data', models.JSONField(default=tracking.models.default_tracking_data)),
                ('tracking_history_data', models.JSONField(default=tracking.models.default_tracking_history)),
                ('tracking_start_location', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('tracking_end_location', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('tracking_start_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tracking_end_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tracking_updated_at', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('trip_ended', models.BooleanField(db_index=True, default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tracking_game', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gameData.game')),
                ('tracking_route', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='routes.route')),
                ('tracking_trip', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tracking.trip')),
                ('tracking_vehicle', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fleet.fleet')),
            ],
            options={
                'verbose_name': 'historical tracking',
                'verbose_name_plural': 'historical trackings',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTrip',
            fields=[
                ('trip_id', models.IntegerField(blank=True, db_index=True)),
                ('trip_display_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('trip_route_num', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('trip_start_location', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('trip_end_location', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('trip_start_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('trip_end_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('trip_updated_at', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('trip_ended', models.BooleanField(db_index=True, default=False)),
                ('trip_missed', models.BooleanField(db_index=True, default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('trip_driver', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('trip_route', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='routes.route')),
                ('trip_vehicle', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fleet.fleet')),
            ],
            options={
                'verbose_name': 'historical trip',
                'verbose_name_plural': 'historical trips',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
