# Generated by Django 5.2.14 on 2026-07-11 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0011_blockvehicleswap'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalTrip',
        ),
    ]
