# Generated by Django 5.2.14 on 2026-07-11 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0052_alter_fleet_fleet_number_and_more'),
        ('routes', '0019_historicaltimetableentry_active_and_more'),
        ('tracking', '0012_delete_historicaltrip'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TripArchive',
            fields=[
                ('archive_id', models.AutoField(primary_key=True, serialize=False)),
                ('original_trip_id', models.IntegerField(db_index=True)),
                ('trip_display_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('trip_route_num', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('trip_start_location', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('trip_end_location', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('trip_start_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('trip_end_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('trip_updated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('trip_ended', models.BooleanField(db_index=True, default=False)),
                ('trip_missed', models.BooleanField(db_index=True, default=False)),
                ('trip_inbound', models.BooleanField(blank=True, db_index=True, null=True)),
                ('archived_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('trip_board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='routes.duty')),
                ('trip_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('trip_route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='routes.route')),
                ('trip_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.fleet')),
            ],
            options={
                'indexes': [models.Index(fields=['original_trip_id'], name='tracking_tr_origina_921a2d_idx'), models.Index(fields=['-trip_end_at'], name='tracking_tr_trip_en_bd3d1e_idx')],
            },
        ),
    ]
