# Generated by Django 5.2.14 on 2026-07-11 06:08

from django.conf import settings
from django.db import migrations, models
from django.contrib.postgres.operations import AddIndexConcurrently


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('fleet', '0052_alter_fleet_fleet_number_and_more'),
        ('routes', '0019_historicaltimetableentry_active_and_more'),
        ('tracking', '0013_triparchive'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL("SET statement_timeout = 0;"),
        AddIndexConcurrently(
            model_name='trip',
            index=models.Index(fields=['trip_end_at', 'trip_updated_at'], name='tracking_tr_trip_en_df0266_idx'),
        ),
        migrations.RunSQL("RESET statement_timeout;"),
    ]
