# Generated by Django 5.2.14 on 2026-07-14 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0013_triparchive 2'),
        ('tracking', '0014_trip_tracking_tr_trip_en_df0266_idx'),
    ]

    operations = [
    ]
