# Generated by Django 5.2.14 on 2026-07-14 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0052_alter_fleet_fleet_number_and_more'),
        ('routes', '0020_add_route_indexes'),
        ('tracking', '0015_merge_20260714_1412'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='triparchive',
            name='trip_board',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='routes.duty'),
        ),
        migrations.AlterField(
            model_name='triparchive',
            name='trip_driver',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='triparchive',
            name='trip_route',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='routes.route'),
        ),
        migrations.AlterField(
            model_name='triparchive',
            name='trip_vehicle',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.fleet'),
        ),
    ]
