# Generated by Django 5.2.14 on 2026-08-18 11:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('fleet', '0059_fleet_engine_gearbox_door'),
        ('routes', '0022_add_routestop_unique_constraint'),
        ('tracking', '0016_alter_triparchive_trip_board_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['trip_start_at', 'trip_missed', 'trip_vehicle_id'], name='trip_start_missed_vehicle_idx'),
        ),
    ]
