# Generated by Django 5.2.16 on 2026-08-22 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0062_operatortransferrequest_unique_pending_operator'),
        ('tracking', '0017_trip_start_missed_vehicle_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveTrip',
            fields=[
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tracking.trip')),
                ('start_datetime', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('end_datetime', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('starts_at', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('ends_at', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('track_route', models.JSONField(blank=True, default=dict)),
                ('track_timing', models.JSONField(blank=True, default=dict)),
                ('computed_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.fleet')),
            ],
        ),
    ]
