# Generated by Django 5.2.3 on 2025-08-24 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_assigned_agent_ticket_assigned_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='discord_channel_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
