# Generated by Django 5.2.3 on 2025-08-24 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_tickettype_discord_channel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='discord_channel_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
