# Generated by Django 5.2.3 on 2025-08-24 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_discord_channel_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickettype',
            old_name='discord_channel_id',
            new_name='discord_category_id',
        ),
    ]
