# Generated by Django 5.2.3 on 2025-08-24 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_rename_discord_channel_id_tickettype_discord_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmessage',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
