# Generated by Django 5.2.3 on 2025-09-10 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_ticketmessage_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='sender_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
