# Generated by Django 5.2.3 on 2025-10-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_historicalad_historicalbadge_historicalbannedips_and_more'),
        ('tickets', '0010_ticket_other_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='other_team',
        ),
        migrations.AddField(
            model_name='tickettype',
            name='other_team',
            field=models.ManyToManyField(blank=True, related_name='other_team_tickets', to='main.mbtteam'),
        ),
    ]
